### ISSUE TITLE
fix is_valid_mem_range() and is_valid_disk_range()

### ISSUE THREAD

**Issue by misterlihao** [GlacierW/MBA#11]
Here is the code,
```c
static int is_valid_mem_range( uint64_t addr, uint64_t len ) {

    if( phys_ram_size - addr < len )
        return false;
    return true;
}
```
When *addr* is larger than *phys_ram_size*,  
the function returns *true*, whether it should return *false*.

There is a same problem in *is_valid_disk_range()* too.

**Comment by hackjackhack** [comment]
Issues are not supposed to be used like this. If you'd like to contribute, please use PR.
Also, provide more information about the change you are going to make.
