### ISSUE TITLE
Fix dift_contaminate_memory_and() and dift_contaminate_memory_or() to support contaminate memory more than 4G 

### ISSUE THREAD

**Issue by Bletchley13** [GlacierW/MBA#2]
**dift_contaminate_memory_*** functions have a while loop to process taint contaminate for each **len_pt_max** size.
But the base address **addr** never added in the while loop, so the taint contaminate will not work when **len** > **len_pt_max**.
[https://github.com/GlacierW/MBA/commit/93ac6367739cba848e6f2c6a59bf21c958b85030#diff-1af4ba10d419d9b4c994b320c09e4e87R1022](url)

```
while( len > 0 ) {
        
        len_pt = (len > len_pt_max)? len_pt_max : len;
        
        *((uint64_t*)&rec) |= ((0x00000000000000ff & tag)    << 8);
        *((uint64_t*)&rec) |= ((0x00000000ffffffff & len_pt) << 16);

        dift_rec_enqueue( *((uint64_t*)&rec) );
        dift_rec_enqueue( addr );

        len -= len_pt;
    } 
```

**Comment by GlacierW** [comment]
A patch has been committed ([ccc3b5e](https://github.com/GlacierW/MBA/commit/ccc3b5e624f866e686581eda1ce81c9dcdca7925)). 
However, the test cases is not implemented yet.
This issue will stay until the testing is completed.
