### ISSUE TITLE
A Dockerfile for MBA?

### ISSUE THREAD

**Issue by bruce30262** [GlacierW/MBA#47]
I think a Dockerfile will be nice  
Even nicer if we can pull the latest docker image of MBA from [dockerhub](https://hub.docker.com/) :)  
What do you guys think ?

**Comment by GlacierW** [comment]
Yes, we will support the docker deployment for MBA after the release of the first stable version.

**Comment by bruce30262** [comment]
@GlacierW cool ! Let's leave this issue open as a reminder.
