### ISSUE TITLE
[Bug] The connection to the agent server is broken while reading

### ISSUE THREAD

**Issue by bruce30262** [GlacierW/MBA#48]
### Expected behavior  
I was about to use `mba_wexec cmd.exe` to check the Dekstop in the guest OS (Win10) after I imported an [img](http://i.imgur.com/Hp0JVgG.png) to the guest OS by using the following command : 
`mba_wimpo /home/bruce30262/MBA-workspace/test-sample/789.PNG C:\Users\dsns\Desktop\789.PNG`  

I was expecting MBA will give me a shell to interact with the guest OS.

### Actual behavior  
It print out the following error message: 
```
The connection to the agent server is broken while reading
```  
Then the whole sandbox was stuck at the `(agent-exec)` prompt. The only thing I can do is kill the MBA process and restart the whole sandbox. 

### Steps to reproduce the problem  
```
$ cat run_mba.sh 
#!/bin/bash
$HOME/MBA/x86_64-softmmu/qemu-system-x86_64 -vnc :2 -monitor stdio -m 2048 -netdev user,id=mynet -device rtl8139,netdev=mynet $HOME/MBA-workspace/win10.qcow2 -loadvm ready  

$ ./run_mba.sh
QEMU 2.3.50 monitor - type 'help' for more information
(qemu) mba_load_structures type_definition
(qemu) KPCR found fffff801a9173000

(qemu) mba_load_structures network_type_definition
(qemu) mba_load_global_variable global_type_definition
(qemu) mba_winit
Agent thread starting
(qemu) mba_wexec cmd.exe
(agent-exec) Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\dsns>
(agent-exec) 
C:\Users\dsns>dir
(agent-exec) dir
 Volume in drive C has no label.
 Volume Serial Number is 3E03-29AC

 Directory of C:\Users\dsns

2016/11/12  �W�06:09    <DIR>          .
2016/11/12  �W�06:09    <DIR>          ..
2016/06/30  �W�04:19    <DIR>          Contacts
2016/06/30  �W�04:19    <DIR>          Desktop
2016/07/14  �W�04:52    <DIR>          Documents
2016/06/30  �W�04:19    <DIR>          Downloads
2016/06/30  �W�04:19    <DIR>          Favorites
2016/06/30  �W�04:19    <DIR>          Links
2016/06/30  �W�04:19    <DIR>          Music
2016/11/05  �W�06:10    <DIR>          OneDrive
2016/06/30  �W�04:19    <DIR>          Pictures
2016/06/30  �W�04:19    <DIR>          Saved Games
2016/06/30  �W�04:19    <DIR>          Searches
2016/06/30  �W�04:19    <DIR>          Videos
2016/11/12  �W�06:07           159,454 win_agent.exe
               1 File(s)        159,454 bytes
              14 Dir(s)   4,785,410,048 bytes free

C:\Users\dsns>
(agent-exec) 
C:\Users\dsns>exit
(agent-exec) exit
System Receive : exec cmd.exe

(qemu) mba_wimpo /home/bruce30262/MBA-workspace/test-sample/789.PNG C:\Users\dsns\Desktop\789.PNG
(qemu) System Receive : impo C:\Users\dsns\Desktop\789.PNG
(qemu) mba_wexec cmd.exe
(agent-exec) The connection to the agent server is broken while reading

(agent-exec) exit
(agent-exec) 
(agent-exec) 
(agent-exec) ./run_mba.sh: line 2:  3192 Killed                  $HOME/MBA/x86_64-softmmu/qemu-system-x86_64 -vnc :2 -monitor stdio -m 2048 -netdev user,id=mynet -device rtl8139,netdev=mynet $HOME/MBA-work
space/win10.qcow2 -loadvm ready
```   
I've used RealVNC to make sure that the image has been imported to the guest OS:  
<img width="404" alt="555" src="https://cloud.githubusercontent.com/assets/4478350/26089555/61776784-3a31-11e7-955e-79fcc4a2d041.PNG">

### Specification on the environment  
I'm running a Linux VM (Ubuntu 14.04 64 bit) on a Windows 10 x64 OS  
```
$ uname -a
Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```  
Inside the VM I run the MBA sandbox, which was built with the latest version of source code:  
```
$ git clone https://github.com/GlacierW/MBA.git
$ ./configure --enable-mba-all --target-list=x86_64-softmmu
$ make -j8
```

**Comment by bruce30262** [comment]
So I've been testing the `mba_wimpo` command with different file types and have discovered an interesting result: **It only broke the agent server after I tried to import an image.**  I've tried to import the following file type:  
* Windows executable (PE file)  
* Media file (`.mp3` , `.flv`)  
* Document (`.doc`, `.pdf`, `.txt`)  
* Compressed file (`.rar`)  
 
All of them have been successfully imported to the guest OS and I could still interact with `cmd.exe` by using the `mba_wexec cmd.exe` command.  However, when I tried to import the image file (`.png`, `.jpg`), it broke the agent server.

**Comment by bruce30262** [comment]
OK so I tried to debug the qemu binary with gdb, and found some really weird behavior :  
  
Normally during the execution of the `mba_wexec cmd.exe` command, it will run to [line 144 in agent.c](https://github.com/GlacierW/MBA/blob/master/ext/agent/agent.c#L144).
During the `sys_recvfrom` syscall, it will write the string "SUCCESS" to the recv buffer, and return the received length `0x8`.  

But after I import an image to the guest OS and run the `mba_wexec cmd.exe` command, the  `sys_recvfrom` syscall behaved strangely: **it will still write the string "SUCCESS" to the recv buffer, but then return the value `0xffffffffffffffea` instead of `0x8`**. This eventually making the `recvfrom()` function call return `-1` and cause the agent server to stop running.  

Not sure why it behaved like this. Please tell me it has nothing to do with the kernel's version :worried:

**Comment by GlacierW** [comment]
Could you provide the image file?
It might be the agent server implementation that causes the bug.
We will have it a closer inspection.

**Comment by GlacierW** [comment]
The bug has been reproduced in our development environment. 
The .PNG image file can be download [here](http://i.imgur.com/Hp0JVgG.png)

The agent log after the bug is triggered:
![2017-05-17_132413](https://cloud.githubusercontent.com/assets/9245070/26142243/519bef7e-3b12-11e7-8d43-70a8f47afeaa.png)

**Comment by GlacierW** [comment]
The bug caused by uninitialized variable has been fixed. 
Please refer to the PR #51 for more detail. Issue closed.
