### ISSUE TITLE
libcfile errors due to "error Missing file remove function"

### ISSUE THREAD

**Issue by Bletchley13** [GlacierW/MBA#7]
The compilation of libqcow fails, due to the new feature of sub-component libcfile.

    libcfile_support.c:742:2: error: #error Missing file remove function
    #error Missing file remove function
      ^ 
    make[2]: *** [libcfile_support.lo] Error 1 
    make[2]: Leaving directory `/tmp/MBA/ext/tsk/sleuthkit/libqcow/libcfile'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/tmp/MBA/ext/tsk/sleuthkit/libqcow' 
    make: *** [ext/tsk/sleuthkit/libqcow/libqcow/.libs/libqcow.a] Error 2

**Comment by Bletchley13** [comment]
This problem is fixed in  #9 , [commit c96a842].(https://github.com/GlacierW/MBA/commit/c96a8427fd66385175957313e047d8d4acf7ebcd)
Current solution is manually updating all files of libqcow to the newest version.
In the future development, an automatic solution is needed.

**Comment by GlacierW** [comment]
The patch has been tested. Issue closed.
